# Generated by Django 4.2.5 on 2023-09-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=255)),
                ('ratings', models.PositiveIntegerField(default=0)),
                ('average', models.PositiveIntegerField(default=0)),
                ('pages', models.PositiveIntegerField()),
                ('pages_read', models.PositiveIntegerField()),
                ('first_published', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
