# Generated by Django 4.2.5 on 2023-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlyreading',
            name='books',
            field=models.ManyToManyField(blank=True, to='config.book'),
        ),
        migrations.AlterField(
            model_name='read',
            name='books',
            field=models.ManyToManyField(blank=True, to='config.book'),
        ),
        migrations.AlterField(
            model_name='wanttoread',
            name='books',
            field=models.ManyToManyField(blank=True, to='config.book'),
        ),
    ]
