# Generated by Django 4.2.5 on 2023-09-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_currentlyreading_books_alter_read_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages_read',
        ),
        migrations.AddField(
            model_name='review',
            name='pages_read',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
