# Generated by Django 4.2.5 on 2023-09-08 07:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
    ]
