# Generated by Django 4.2.5 on 2023-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_book_genre_currentlyreading_user_read_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
